name: Cavendish
favicon: null
layout_spectrum: 0.414704441325739
typography_spectrum: 0.9980048534926027
title: Een duo dat elkaar na meer dan 25 jaar teruggevonden heeft…
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
  brandStrength: 0.5896959744859487
  lightness: 0.7048731478862464
  saturation: 0.15346600324846804
  rhythmicContrast: 0.3280322412028909
purpose: []
