name: Cavendish
favicon: null
layout_spectrum: 0.414704441325739
typography_spectrum: 0.09637
title: Een duo dat elkaar na meer dan 25 jaar terug vond …
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
  brandStrength: 0.5896959744859487
  lightness: 0.375
  saturation: 0.1875
  rhythmicContrast: 0.25
purpose: []
